"""update tailored jobs table

Revision ID: 2b96e03863df
Revises: 511390dfad19
Create Date: 2026-07-15 22:09:13.426046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b96e03863df'
down_revision: Union[str, Sequence[str], None] = '511390dfad19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailor_jobs', sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('tailor_jobs', 'result_filename')
    op.drop_column('tailor_jobs', 'status')
    op.drop_column('tailor_jobs', 'result_pdf')
    op.drop_column('tailor_jobs', 'error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailor_jobs', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tailor_jobs', sa.Column('result_pdf', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('tailor_jobs', sa.Column('status', postgresql.ENUM('PENDING', 'DONE', 'ERROR', name='tailor_status'), autoincrement=False, nullable=False))
    op.add_column('tailor_jobs', sa.Column('result_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('tailor_jobs', 'result_data')
    # ### end Alembic commands ###
