"""add name and email columns to profile

Revision ID: 511390dfad19
Revises: 71353a403e76
Create Date: 2026-07-15 05:07:47.717540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "511390dfad19"
down_revision: Union[str, Sequence[str], None] = "71353a403e76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("name", sa.String(length=32), nullable=True))
    op.add_column("profiles", sa.Column("email", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "email")
    op.drop_column("profiles", "name")
    # ### end Alembic commands ###
