"""update missing skills column to array of str

Revision ID: 688f8038af08
Revises: 2b96e03863df
Create Date: 2026-07-15 22:17:28.504340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688f8038af08'
down_revision: Union[str, Sequence[str], None] = '2b96e03863df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tailor_jobs', 'missing_skills',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="string_to_array(missing_skills, ', ')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tailor_jobs', 'missing_skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using="array_to_string(missing_skills, ', ')")
    # ### end Alembic commands ###
