"""add password_hash to profile

Revision ID: a8f3cd87ac2a
Revises: 1ae46db0a437
Create Date: 2026-08-20 00:54:41.954119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f3cd87ac2a'
down_revision: Union[str, Sequence[str], None] = '1ae46db0a437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'password_hash')
    # ### end Alembic commands ###
